### ISSUE TITLE
Use with expo-sqlite 

### ISSUE THREAD

**Issue by smontlouis** [trong-orm/trong-orm#15]
Awesome library! We've been waiting for this! 

We're looking for a reactive react native library to communicate with sqlite. 

Do you plan on making it compatible with expo-sqlite? May I ask what is your road map?

Thank you.

**Comment by quolpr** [comment]
@smontlouis hey! I am glad that Trong meet your needs 🙂

I was able to connect expo (web and native) with Trong, here you can check example https://github.com/trong-orm/trong-expo-example.

You will need to specify custom webpack config:
https://github.com/trong-orm/trong-expo-example/blob/main/webpack.config.js

And create metro file:
https://github.com/trong-orm/trong-expo-example/blob/main/metro.config.js

**Comment by quolpr** [comment]
As for the plan — add missing parts to query-builder, finish doc, add other platforms support

**Comment by quolpr** [comment]
Here is the guide:

https://trong-orm.netlify.app/react-integration/expo-installation

**Comment by smontlouis** [comment]
This is the best news of the week ! 

I've been delaying the native development of our project for a while now because I couldn't find a good offline-first strategy.
I took a look at watermelonDB, rxdb, realm, etc but for many reasons it was not what I was looking for.
I had some hope when I looked at (riffle)[https://riffle.systems/essays/prelude], but it seems to be still in its early stages.

And I'm very happy to see that you'll add a data sync on top of it, because it was something I was planning to manually handle ;)

**Comment by quolpr** [comment]
> I took a look at watermelonDB, rxdb, realm, etc but for many reasons it was not what I was looking for.

Yep, I too. I was developing https://github.com/quolpr/harika, and decided to move all ideas to Trong ORM 🙂 I tried  watermelonDB, rxdb, realm too, and all of them were missing something. And, overall, IndexedDB just sucks in performance.

Regarding riffle— I am very excited too. There is a presentation that was uploaded recently where you can get some insides — https://www.youtube.com/watch?v=BmgL1SRfUyc

> And I'm very happy to see that you'll add a data sync on top of it, because it was something I was planning to manually handle ;)

I am not sure when I will start working on it and how much time it will take. So I suggest for not is build your own sync system

**Comment by smontlouis** [comment]
All good ! Thanks.

@quolpr may I ask what will be your strategy for the sync system ?
I've been reading a lot of interesting stuff lately, but I'm not sure what would be the best fit.

I took a look at [jlongster's app](https://github.com/jlongster/crdt-example-app) and the database itself is CRDT-like.

I was thinking about having in addition of the regular sql tables a "messages" table that will contain all of the atomic changes happening in the db at a field level, like the crdt-example-app `messages"`table, with the timestamp and such. 

As soon as an insert / update / delete action is performed with trong-orm, a message is sent to the server. If the user is offline, these messages are stored in the "messages" table.
The server would apply changes on the entities that have an updated_at lower than the timestamp of the messages.

It's quite a naive approach, but it's not a collaborative tool, just a multi-device tool with offline support.

Thank you !

**Comment by quolpr** [comment]
@smontlouis good enough 🙂 Actually what I was doing — collecting all the changes on the client, sending to the server, server was recalculating all the changes from the start for a particular entity, and sending back the entity. So there are no conflict should be happened, but some data could unexpectedly rewritten (due to changes for the same field in the entity on two clients when both were offline) — for that case you can implement the time travel (because you have all the changes that were made before) 🙂

**Comment by quolpr** [comment]
I want to implement similar algorithm that I described above on top of the trong-orm
